<!-- Generated by StoryCode v0.1.0 -->
<!-- Source: entire project (47 files) -->
<!-- Provider: claude | Language: estonian | Detail: detailed -->
<!-- Generated: 2026-02-26T09:26:45.420Z -->

# Project Story: Juuksurisalongi Broneerimissüsteem

## What this project does

See projekt on täielik veebirakendus juuksurisalongi jaoks, mis võimaldab klientidel mugavalt broneerida aegu erinevate juuksurite juurde. Süsteem toimib nagu digitaalne vastuvõturegistraator – kliendid saavad valida endale sobiva juuksuri, soovitud teenuse ja vaba aja, samas kui salongi töötajad saavad halduspaneeli kaudu hallata kõiki broneeringuid, juuksureid ja teenuseid. See on nagu kaasaegne versioon traditsioonilisest broneerimisraamatust, kus kõik toimub automaatselt ja võimalikud kokkupõrked aegade broneerimises välditakse nutikate kontrollide abil.

<!-- @source: php/index.php:1-8 -->
<!-- @source: php/config/app.php:3-7 -->

## The big picture

Projekt on ehitatud üles nagu korralik maja, kus igal ruumil on oma kindel otstarve. Peasissepääsu ehk peafaili kaudu käivitub kogu süsteem, mis seejärel jaguneb mitmeks peamiseks tiivaks. Esimene tiib on avalik osa – see on nagu salongi fuajee, kus kliendid saavad lehitseda teenuseid, tutvuda juuksuritega ja broneerida aegu. Teine tiib on haldusosa – see on nagu salongi kontoriruumid, kuhu on ligipääs ainult töötajatel ja kus saab hallata kogu salongi tööd. Kolmas tiib on andmebaas – see on nagu salongi arhiiv, kus hoitakse kõiki olulisi andmeid: kes on juuksurid, millised teenused on saadaval, kes on broneerinud ja millal.

Kõik see toimib koos tänu keskse juhtimissüsteemile, mis koordineerib erinevaid osi. See on nagu direktori assistent, kes teab täpselt, kellele milliseid ülesandeid suunata ja kuidas erinevad osakond omavahel peavad suhtlema.

<!-- @source: php/src/Core/App.php:13-26 -->
<!-- @source: php/src/Core/Database.php:8-35 -->

## How it all works together

Kui keegi avab salongi veebilehe, algab teekond. Süsteem vaatab kõigepealt, millisele lehele kasutaja soovib minna. Kui see on avaleht, näidatakse kaunist tervitusvaatet koos salongi juuksuritega ja võimalusega kohe broneerima hakata. Siin näidatakse salongi nime, kirjeldust ja kõiki aktiivseid juuksureid nende lühitutvustustega.

<!-- @source: php/src/Core/Router.php:32-54 -->
<!-- @source: php/views/public/home.php:1-50 -->

Kui klient otsustab vaadata teenuseid, viiakse ta teenuste lehele, kus kõik teenused on ilusasti kategooriate kaupa grupeeritud. Iga teenuse juures on näha hinnavahemik – see tuleb sellest, et erinevatel juuksuritel võivad sama teenuse hinnad veidi erineda. Süsteem küsib andmebaasist, millised on kõige odavamad ja kõige kallimad hinnad iga teenuse kohta ning näitab seda vahemikuna.

<!-- @source: php/src/Controllers/PageController.php:25-50 -->
<!-- @source: php/views/public/services.php:1-50 -->

Päris huvitavaks läheb asi siis, kui klient vajutab "Broneeri aeg" nupule. Avaneb samm-sammult juhendatud protsess, mida võib võrrelda reisibüroo töötajaga, kes küsib järjest õigeid küsimusi. Esimene samm: vali juuksur. Süsteem laeb kõik aktiivsed juuksurid ja näitab neid kaartidel koos nende nimedega ja kirjeldustega. Kui klient valib juuksuri, küsib süsteem kohe, millised teenused see juuksur osutab. 

<!-- @source: php/public/js/booking.js:20-65 -->
<!-- @source: php/views/public/booking/index.php:28-41 -->

Teine samm: vali teenus. Nüüd näidatakse ainult neid teenuseid, mida valitud juuksur teeb, koos täpsete hindade ja kestustega. Iga juuksur võib sama teenust pakkuda erinevate hindadega või see võib võtta erineva aja – näiteks üks juuksur teeb lõikuse 30 minutiga 25 euro eest, teine 45 minutiga 30 euro eest.

<!-- @source: php/public/js/booking.js:67-103 -->

Kolmas samm on kõige keerulisem ja huvitavam: vali kuupäev ja kellaaeg. Siin hakkab süsteem töötama nagu osav assistentklassi õpetaja, kes peab koostama tunniplaani. Kui klient valib kuupäeva, käivitub kogu masinavärk. Süsteem kontrollib, milline päev see on (esmaspäev, teisipäev jne), vaatab, kas juuksur sel päeval üldse töötab, millised on tema töötunnid, kas tal on lõunapause või muid pause, ja millised ajad on juba broneeritud teiste klientide poolt.

<!-- @source: php/public/js/booking.js:115-176 -->
<!-- @source: php/src/Services/TimeSlotService.php:11-130 -->

See ajavahemike arvutamine on nagu pusle kokkupanemine. Esmalt võtab süsteem juuksuri töötunnid – näiteks 9:00 kuni 18:00. Siis vaatab, kas on lõunapaus – näiteks 12:00 kuni 13:00. Siis kontrollib kõiki olemasolevaid broneeringuid. Kui keegi on broneerinud 10:00-11:00, siis seda aega enam ei pakuta. Süsteem arvestab ka teenuse kestusega – kui teenus võtab 45 minutit ja kell on juba 17:30, siis ei näidata enam vaba aega, sest juuksur lõpetab töö kell 18:00 ja ei jõuaks teenust lõpule viia.

Samuti on kaval kontroll: kui praegu on kell 14:00 ja salongi reeglites on kirjas, et broneerida saab vähemalt tund ette, siis kõik ajad enne 15:00 jäävad varjatuks. See kaitseb seda, et keegi ei broneeriks aega, milleks juuksur ei jõuaks valmistuda.

<!-- @source: php/src/Services/TimeSlotService.php:41-111 -->

Neljas samm: sisesta oma andmed. Nüüd näidatakse kliendile kaunist kokkuvõtet – keda ta valis, millist teenust, millal ja kui palju see maksab. All on vormid, kuhu sisestada oma nimi, telefon, e-post ja võimalikud lisasoovid.

<!-- @source: php/views/public/booking/index.php:60-108 -->

Kui klient vajutab "Kinnita broneering", juhtub huvitav asi. Süsteem saadab andmed serverile, kuid enne nende salvestamist käivitub terve turvasüsteem. Esiteks kontrollitakse, kas vorm tuleb päriselt sellelt veebilehelt ja mitte mõnest teisest kohast (see on nagu uksekilp, mis kontrollib, kas külaline on kutsutud). Teiseks kontrollitakse kõiki andmeid – kas nimi on piisavalt pikk, kas telefon on õiges formaadis, kas kuupäev on kehtiv.

<!-- @source: php/src/Controllers/BookingController.php:26-59 -->
<!-- @source: php/src/Core/Validator.php:9-121 -->

Siis tuleb kõige olulisem osa: süsteem peab veenduma, et valitud aeg on ikka veel vaba. Kujuta ette, et kaks inimest tahavad samal ajal sama juuksuri juurde tulla. Mõlemad avastavad, et kell 15:00 on vaba, ja mõlemad üritavad sama aega broneerida. Et vältida seda, et mõlemad saaksid broneeringu kinnituse, kasutab süsteem nutikust nimega "andmebaasi lukustus". See on nagu ukse peale pannud "Ärge segake" silt – enne kui esimene broneering on täielikult läbi viidud, ei lase süsteem teisel inimesel isegi proovida sama aega broneerida. Kui esimene on lõpetanud, võib teine proovida, aga siis näeb ta, et see aeg on juba hõivatud, ja peab valima mõne teise aja.

<!-- @source: php/src/Models/Appointment.php:73-147 -->

Pärast edukat broneerimist näeb klient kinnitusvaate suure rohelise linnukesega ja kõigi andmete kinnitust. Samas salvestatakse kogu info andmebaasi, kust seda saavad hiljem vaadata salongi töötajad.

<!-- @source: php/public/js/booking.js:244-262 -->
<!-- @source: php/views/public/booking/index.php:110-117 -->

Nüüd jõuame halduspaneeli juurde. See on eraldi maailm, kuhu pääsevad ligi ainult salongi töötajad. Et sinna sisse saada, peab sisestama e-posti aadressi ja parooli. Süsteem võrdleb neid andmebaasis olevate andmetega, kontrollib parooli turvaliselt (parool ei ole andmebaasis nähtav, ainult selle krüpteeritud versioon), ja kui kõik on õige, lubatakse sisse. Oluline on ka see, et pärast sisselogimist vahetatakse välja sessiooninumber – see takistab teatud tüüpi küberkurjategijatel sisse murda.

<!-- @source: php/src/Controllers/AdminAuthController.php:27-60 -->
<!-- @source: php/src/Models/User.php:9-17 -->

Halduspaneeli avavaade on nagu lennujaama infotahvel – näitab kõige olulisemat infot ühe pilguga. Mitu broneeringut on täna, mitu sel nädalal, mitu aktiivset juuksurit on, ja nimekiri lähiajal tulemasolevast broneeringutest. See annab kiire ülevaate, kuidas asjad lähevad.

<!-- @source: php/src/Controllers/AdminAppointmentController.php:13-29 -->
<!-- @source: php/views/admin/dashboard.php:1-59 -->

Broneeringute lehel saavad töötajad näha kõiki broneeringuid tabelina, filtreerida neid kuupäeva või staatuse järgi (kinnitatud, tehtud, tühistatud, klient ei tulnud). Iga broneeringu kohta on näha kõik olulised andmed, ja klõpsates broneeringu peale avaneb täpsem vaade, kus on võimalik broneeringu staatust muuta. Kui klient helistab ja ütleb, et ei saa tulla, võib töötaja märkida broneeringu tühistatuks. Kui teenus on tehtud, võib märkida tehtud staatuseks. See aitab pidada arvestust ja annab statistikat, kui palju kliente tegelikult käib.

<!-- @source: php/src/Controllers/AdminAppointmentController.php:31-52 -->
<!-- @source: php/views/admin/appointments/index.php:1-90 -->
<!-- @source: php/src/Controllers/AdminAppointmentController.php:76-98 -->

Juuksurite haldamine on nagu personali kataloog. Siin saab lisada uusi juuksureid, muuta nende andmeid, määrata, millised teenused nad pakuvad ja milliste hindadega, ning seadistada nende töögraafikut. Eriti huvitav on pauside süsteem – iga juuksuri kohta saab määrata, millistel nädalapäevadel on tal lõunapaus või muud pausid. Näiteks esmaspäevast reedeni kell 12:00-13:00 on lõuna, laupäeval 11:00-11:30 kohvipaus. Need pausid võetakse arvesse automaatselt, kui kliendid valivad broneerimiseks aega.

<!-- @source: php/src/Controllers/AdminBarberController.php:32-91 -->
<!-- @source: php/views/admin/barbers/form.php:53-110 -->
<!-- @source: php/src/Models/ScheduleBreak.php:9-56 -->

Teenuste haldamine on lihtsam – siin määratakse, millised teenused üldse olemas on (juukselõikus, värvimine, keemiline kohevus jne), mis kategooriasse nad kuuluvad, ja kas nad on aktiivsed või mitte. Konkreetsed hinnad ja kestused määratakse juuksuri juures, sest iga juuksuril võivad need erineda.

<!-- @source: php/src/Controllers/AdminServiceController.php:42-82 -->
<!-- @source: php/views/admin/services/form.php:1-59 -->

Kogu süsteem on ehitatud turvalisust silmas pidades. Iga kord, kui midagi muudetakse või kustutatakse, kontrollitakse turvakoodi (CSRF token), mis kaitseb selle eest, et keegi ei saaks pahatahtlikult teiste arvutist andmeid muuta. Igal halduspaneeli lehel kontrollitakse, kas kasutaja on ikka sisse loginud, ja kui ei ole, suunatakse ta automaatselt sisselogimise lehele.

<!-- @source: php/src/Core/Controller.php:31-54 -->
<!-- @source: php/src/Core/Session.php:52-66 -->

Andmebaasiga suhtlemine toimub läbi turvalist kanalit, mis kaitseb SQL-süstimiste vastu. Iga kord, kui midagi andmebaasist küsitakse või sinna salvestatakse, kasutatakse ettevalmistatud päringuid, mis tähendab, et kasutaja sisestatud andmed ei saa kunagi juhuslikult käskudeks muutuda.

<!-- @source: php/src/Core/Database.php:12-35 -->

## The key players

**Peasüsteem ja marsruuter** – See on nagu salongi vastuvõtulett. Kui keegi tuleb sisse (avab veebilehe), vaatab süsteem, mida nad tahavad (millist lehte nad tahavad näha), ja saadab nad õigesse